# Auto-merge PRs from DeepSource autofix bot
# This workflow automatically merges code quality improvements from DeepSource
# Only PRs from the deepsource-autofix[bot] user will be processed

name: Auto-merge DeepSource PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge-deepsource:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'deepsource-autofix[bot]'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify PR author
        run: |
          PR_AUTHOR="${{ github.event.pull_request.user.login }}"
          echo "PR Author: $PR_AUTHOR"
          if [[ "$PR_AUTHOR" != "deepsource-autofix[bot]" ]]; then
            echo "PR is not from DeepSource bot, skipping"
            exit 1
          fi

      - name: Verify PR content
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          echo "PR Title: $PR_TITLE"
          if [[ "$PR_TITLE" != *"style:"* && "$PR_TITLE" != *"fix:"* && "$PR_TITLE" != *"refactor:"* ]]; then
            echo "PR title doesn't match expected DeepSource format, but proceeding anyway"
          fi

      - name: Wait for status checks
        run: |
          echo "Waiting for status checks to complete..."
          # Wait up to 5 minutes for checks to complete
          timeout=300
          while [ $timeout -gt 0 ]; do
            # Check if PR is mergeable and all checks passed
            MERGEABLE=$(gh pr view ${{ github.event.pull_request.number }} --json mergeable,mergeStateStatus --jq '.mergeable, .mergeStateStatus')
            if [[ "$MERGEABLE" == *"MERGEABLE"* ]] && [[ "$MERGEABLE" == *"CLEAN"* ]]; then
              echo "PR is ready to merge!"
              break
            fi
            echo "Waiting for PR to be ready... ($timeout seconds remaining)"
            sleep 30
            timeout=$((timeout - 30))
          done

          if [ $timeout -le 0 ]; then
            echo "Timeout waiting for PR to be mergeable"
            exit 1
          fi

      - name: Auto-merge DeepSource PR
        run: |
          echo "Auto-merging DeepSource PR #${{ github.event.pull_request.number }}"
          gh pr merge ${{ github.event.pull_request.number }} --auto --merge

      - name: Clean up merged branch
        run: |
          # Get the branch name from the PR
          BRANCH_NAME=$(gh pr view ${{ github.event.pull_request.number }} --json headRefName --jq '.headRefName')
          echo "Cleaning up branch: $BRANCH_NAME"

          # Only delete if it's not a protected branch and not main/master
          if [[ "$BRANCH_NAME" != "main" && "$BRANCH_NAME" != "master" && "$BRANCH_NAME" == *"deepsource"* ]]; then
            echo "Deleting branch: $BRANCH_NAME"
            git push origin --delete "$BRANCH_NAME" || echo "Branch may have been already deleted"
          else
            echo "Skipping branch deletion for: $BRANCH_NAME"
          fi