name: No-Emoji Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  check-no-emojis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install
        run: |
          python -m pip install --upgrade pip
      - name: Run no-emoji checker
        run: |
          python scripts/check_no_emojis.py